/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as ApiInviteNotificationRouteImport } from './routes/api.invite-notification'
import { Route as ApiLeaveDecisionNotificationRouteImport } from './routes/api.leave-decision-notification'
import { Route as ApiLeaveNotificationRouteImport } from './routes/api.leave-notification'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminCompanyRouteImport } from './routes/_authenticated/admin.company'
import { Route as AuthenticatedAdminDepartmentsRouteImport } from './routes/_authenticated/admin.departments'
import { Route as AuthenticatedAdminEmployeesRouteImport } from './routes/_authenticated/admin.employees'
import { Route as AuthenticatedAdminLateRouteImport } from './routes/_authenticated/admin.late'
import { Route as AuthenticatedAdminLeavesRouteImport } from './routes/_authenticated/admin.leaves'
import { Route as AuthenticatedAdminNoticesRouteImport } from './routes/_authenticated/admin.notices'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin.support'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAppExtraRouteImport } from './routes/_authenticated/app.extra'
import { Route as AuthenticatedAppLeaveRouteImport } from './routes/_authenticated/app.leave'
import { Route as AuthenticatedAppNoticesRouteImport } from './routes/_authenticated/app.notices'
import { Route as AuthenticatedAppPunchRouteImport } from './routes/_authenticated/app.punch'
import { Route as AuthenticatedAdminEmployeesIdRouteImport } from './routes/_authenticated/admin.employees.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiInviteNotificationRoute = ApiInviteNotificationRouteImport.update({
  id: '/api/invite-notification',
  path: '/api/invite-notification',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeaveDecisionNotificationRoute =
  ApiLeaveDecisionNotificationRouteImport.update({
    id: '/api/leave-decision-notification',
    path: '/api/leave-decision-notification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLeaveNotificationRoute = ApiLeaveNotificationRouteImport.update({
  id: '/api/leave-notification',
  path: '/api/leave-notification',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCompanyRoute =
  AuthenticatedAdminCompanyRouteImport.update({
    id: '/company',
    path: '/company',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDepartmentsRoute =
  AuthenticatedAdminDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmployeesRoute =
  AuthenticatedAdminEmployeesRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLateRoute = AuthenticatedAdminLateRouteImport.update({
  id: '/late',
  path: '/late',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminLeavesRoute =
  AuthenticatedAdminLeavesRouteImport.update({
    id: '/leaves',
    path: '/leaves',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNoticesRoute =
  AuthenticatedAdminNoticesRouteImport.update({
    id: '/notices',
    path: '/notices',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAppExtraRoute = AuthenticatedAppExtraRouteImport.update({
  id: '/extra',
  path: '/extra',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppLeaveRoute = AuthenticatedAppLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppNoticesRoute = AuthenticatedAppNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPunchRoute = AuthenticatedAppPunchRouteImport.update({
  id: '/punch',
  path: '/punch',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAdminEmployeesIdRoute =
  AuthenticatedAdminEmployeesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminEmployeesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/api/invite-notification': typeof ApiInviteNotificationRoute
  '/api/leave-decision-notification': typeof ApiLeaveDecisionNotificationRoute
  '/api/leave-notification': typeof ApiLeaveNotificationRoute
  '/invite/$token': typeof InviteTokenRoute
  '/admin/company': typeof AuthenticatedAdminCompanyRoute
  '/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesRouteWithChildren
  '/admin/late': typeof AuthenticatedAdminLateRoute
  '/admin/leaves': typeof AuthenticatedAdminLeavesRoute
  '/admin/notices': typeof AuthenticatedAdminNoticesRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/app/extra': typeof AuthenticatedAppExtraRoute
  '/app/leave': typeof AuthenticatedAppLeaveRoute
  '/app/notices': typeof AuthenticatedAppNoticesRoute
  '/app/punch': typeof AuthenticatedAppPunchRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/employees/$id': typeof AuthenticatedAdminEmployeesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/api/invite-notification': typeof ApiInviteNotificationRoute
  '/api/leave-decision-notification': typeof ApiLeaveDecisionNotificationRoute
  '/api/leave-notification': typeof ApiLeaveNotificationRoute
  '/invite/$token': typeof InviteTokenRoute
  '/admin/company': typeof AuthenticatedAdminCompanyRoute
  '/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesRouteWithChildren
  '/admin/late': typeof AuthenticatedAdminLateRoute
  '/admin/leaves': typeof AuthenticatedAdminLeavesRoute
  '/admin/notices': typeof AuthenticatedAdminNoticesRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/app/extra': typeof AuthenticatedAppExtraRoute
  '/app/leave': typeof AuthenticatedAppLeaveRoute
  '/app/notices': typeof AuthenticatedAppNoticesRoute
  '/app/punch': typeof AuthenticatedAppPunchRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/employees/$id': typeof AuthenticatedAdminEmployeesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/api/invite-notification': typeof ApiInviteNotificationRoute
  '/api/leave-decision-notification': typeof ApiLeaveDecisionNotificationRoute
  '/api/leave-notification': typeof ApiLeaveNotificationRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_authenticated/admin/company': typeof AuthenticatedAdminCompanyRoute
  '/_authenticated/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/_authenticated/admin/employees': typeof AuthenticatedAdminEmployeesRouteWithChildren
  '/_authenticated/admin/late': typeof AuthenticatedAdminLateRoute
  '/_authenticated/admin/leaves': typeof AuthenticatedAdminLeavesRoute
  '/_authenticated/admin/notices': typeof AuthenticatedAdminNoticesRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/app/extra': typeof AuthenticatedAppExtraRoute
  '/_authenticated/app/leave': typeof AuthenticatedAppLeaveRoute
  '/_authenticated/app/notices': typeof AuthenticatedAppNoticesRoute
  '/_authenticated/app/punch': typeof AuthenticatedAppPunchRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/employees/$id': typeof AuthenticatedAdminEmployeesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/app'
    | '/api/invite-notification'
    | '/api/leave-decision-notification'
    | '/api/leave-notification'
    | '/invite/$token'
    | '/admin/company'
    | '/admin/departments'
    | '/admin/employees'
    | '/admin/late'
    | '/admin/leaves'
    | '/admin/notices'
    | '/admin/reports'
    | '/admin/support'
    | '/admin/users'
    | '/app/extra'
    | '/app/leave'
    | '/app/notices'
    | '/app/punch'
    | '/admin/'
    | '/admin/employees/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app'
    | '/api/invite-notification'
    | '/api/leave-decision-notification'
    | '/api/leave-notification'
    | '/invite/$token'
    | '/admin/company'
    | '/admin/departments'
    | '/admin/employees'
    | '/admin/late'
    | '/admin/leaves'
    | '/admin/notices'
    | '/admin/reports'
    | '/admin/support'
    | '/admin/users'
    | '/app/extra'
    | '/app/leave'
    | '/app/notices'
    | '/app/punch'
    | '/admin'
    | '/admin/employees/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/api/invite-notification'
    | '/api/leave-decision-notification'
    | '/api/leave-notification'
    | '/invite/$token'
    | '/_authenticated/admin/company'
    | '/_authenticated/admin/departments'
    | '/_authenticated/admin/employees'
    | '/_authenticated/admin/late'
    | '/_authenticated/admin/leaves'
    | '/_authenticated/admin/notices'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/support'
    | '/_authenticated/admin/users'
    | '/_authenticated/app/extra'
    | '/_authenticated/app/leave'
    | '/_authenticated/app/notices'
    | '/_authenticated/app/punch'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/employees/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiInviteNotificationRoute: typeof ApiInviteNotificationRoute
  ApiLeaveDecisionNotificationRoute: typeof ApiLeaveDecisionNotificationRoute
  ApiLeaveNotificationRoute: typeof ApiLeaveNotificationRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/invite-notification': {
      id: '/api/invite-notification'
      path: '/api/invite-notification'
      fullPath: '/api/invite-notification'
      preLoaderRoute: typeof ApiInviteNotificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leave-decision-notification': {
      id: '/api/leave-decision-notification'
      path: '/api/leave-decision-notification'
      fullPath: '/api/leave-decision-notification'
      preLoaderRoute: typeof ApiLeaveDecisionNotificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leave-notification': {
      id: '/api/leave-notification'
      path: '/api/leave-notification'
      fullPath: '/api/leave-notification'
      preLoaderRoute: typeof ApiLeaveNotificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/company': {
      id: '/_authenticated/admin/company'
      path: '/company'
      fullPath: '/admin/company'
      preLoaderRoute: typeof AuthenticatedAdminCompanyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/departments': {
      id: '/_authenticated/admin/departments'
      path: '/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AuthenticatedAdminDepartmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/employees': {
      id: '/_authenticated/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AuthenticatedAdminEmployeesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/late': {
      id: '/_authenticated/admin/late'
      path: '/late'
      fullPath: '/admin/late'
      preLoaderRoute: typeof AuthenticatedAdminLateRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leaves': {
      id: '/_authenticated/admin/leaves'
      path: '/leaves'
      fullPath: '/admin/leaves'
      preLoaderRoute: typeof AuthenticatedAdminLeavesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notices': {
      id: '/_authenticated/admin/notices'
      path: '/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AuthenticatedAdminNoticesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/app/extra': {
      id: '/_authenticated/app/extra'
      path: '/extra'
      fullPath: '/app/extra'
      preLoaderRoute: typeof AuthenticatedAppExtraRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/leave': {
      id: '/_authenticated/app/leave'
      path: '/leave'
      fullPath: '/app/leave'
      preLoaderRoute: typeof AuthenticatedAppLeaveRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/notices': {
      id: '/_authenticated/app/notices'
      path: '/notices'
      fullPath: '/app/notices'
      preLoaderRoute: typeof AuthenticatedAppNoticesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/punch': {
      id: '/_authenticated/app/punch'
      path: '/punch'
      fullPath: '/app/punch'
      preLoaderRoute: typeof AuthenticatedAppPunchRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/employees/$id': {
      id: '/_authenticated/admin/employees/$id'
      path: '/$id'
      fullPath: '/admin/employees/$id'
      preLoaderRoute: typeof AuthenticatedAdminEmployeesIdRouteImport
      parentRoute: typeof AuthenticatedAdminEmployeesRoute
    }
  }
}

interface AuthenticatedAdminEmployeesRouteChildren {
  AuthenticatedAdminEmployeesIdRoute: typeof AuthenticatedAdminEmployeesIdRoute
}

const AuthenticatedAdminEmployeesRouteChildren: AuthenticatedAdminEmployeesRouteChildren =
  {
    AuthenticatedAdminEmployeesIdRoute: AuthenticatedAdminEmployeesIdRoute,
  }

const AuthenticatedAdminEmployeesRouteWithChildren =
  AuthenticatedAdminEmployeesRoute._addFileChildren(
    AuthenticatedAdminEmployeesRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCompanyRoute: typeof AuthenticatedAdminCompanyRoute
  AuthenticatedAdminDepartmentsRoute: typeof AuthenticatedAdminDepartmentsRoute
  AuthenticatedAdminEmployeesRoute: typeof AuthenticatedAdminEmployeesRouteWithChildren
  AuthenticatedAdminLateRoute: typeof AuthenticatedAdminLateRoute
  AuthenticatedAdminLeavesRoute: typeof AuthenticatedAdminLeavesRoute
  AuthenticatedAdminNoticesRoute: typeof AuthenticatedAdminNoticesRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCompanyRoute: AuthenticatedAdminCompanyRoute,
  AuthenticatedAdminDepartmentsRoute: AuthenticatedAdminDepartmentsRoute,
  AuthenticatedAdminEmployeesRoute:
    AuthenticatedAdminEmployeesRouteWithChildren,
  AuthenticatedAdminLateRoute: AuthenticatedAdminLateRoute,
  AuthenticatedAdminLeavesRoute: AuthenticatedAdminLeavesRoute,
  AuthenticatedAdminNoticesRoute: AuthenticatedAdminNoticesRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppExtraRoute: typeof AuthenticatedAppExtraRoute
  AuthenticatedAppLeaveRoute: typeof AuthenticatedAppLeaveRoute
  AuthenticatedAppNoticesRoute: typeof AuthenticatedAppNoticesRoute
  AuthenticatedAppPunchRoute: typeof AuthenticatedAppPunchRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppExtraRoute: AuthenticatedAppExtraRoute,
  AuthenticatedAppLeaveRoute: AuthenticatedAppLeaveRoute,
  AuthenticatedAppNoticesRoute: AuthenticatedAppNoticesRoute,
  AuthenticatedAppPunchRoute: AuthenticatedAppPunchRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiInviteNotificationRoute: ApiInviteNotificationRoute,
  ApiLeaveDecisionNotificationRoute: ApiLeaveDecisionNotificationRoute,
  ApiLeaveNotificationRoute: ApiLeaveNotificationRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
